-- Create suspensiones table
create table if not exists public.suspensiones (
  id bigint generated by default as identity primary key,
  usuario_id bigint references public.usuarios(id) on delete cascade not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  motivo text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint check_fechas check (fecha_fin >= fecha_inicio)
);

-- Enable RLS
alter table public.suspensiones enable row level security;

-- Policies

-- 1. Read: All authenticated users can read suspensions (needed for checking availability)
create policy "Authenticated users can read suspensions"
  on public.suspensiones for select
  to authenticated
  using (true);

-- 2. Write: Only leaders of "Servidores" department can insert/update/delete
-- Note: This assumes you have a way to check department leadership in RLS or you trust the application layer.
-- For strict RLS, you would need a function or sophisticated join. 
-- For now, we will use a more permissive policy for authenticated users if relies on App logic, 
-- OR use a custom claim/helper function. 
-- Given the complexity of checking "Leader of Servidores" in pure SQL RLS without helper functions, 
-- we will allow authenticated users to Insert/Delete but RELY ON THE APP CAREFULLY.
-- BETTER OPTION: Check if the user is a member of dep 'Servidores' with role 'Líder'.

create or replace function public.is_servidores_leader()
returns boolean as $$
begin
  return exists (
    select 1 from public.membresias m
    join public.departamentos d on m.departamento_id = d.id
    where m.usuario_id = (select id from public.user_profiles where auth_user_id = auth.uid())
    and d.nombre = 'Servidores'
    and lower(m.rol_jerarquico) in ('líder', 'lider', 'sublíder', 'sublider')
  );
end;
$$ language plpgsql security definer;

create policy "Servidores leaders can manage suspensions"
  on public.suspensiones for all
  to authenticated
  using (public.is_servidores_leader())
  with check (public.is_servidores_leader());
