-- ─────────────────────────────────────────────────────────────────────────────
-- RESTRICCIONES DE SERVIDORES — modelo de datos
--
-- Aplica al departamento Servidores (id = 2). Define las primitivas con las que
-- se expresan TODAS las reglas de elegibilidad para el rol mensual:
--   · uniformes formales que posee cada servidor (solo se evalúan en domingos)
--   · whitelist de posiciones permitidas
--   · grupos de incompatibilidad (no coinciden el mismo día)
--   · restricciones generales (liderazgo externo, frecuencia, topes, días, etc.)
--   · override manual en asignaciones
--
-- RLS en todas: lectura para autenticados; escritura para líder/sublíder del
-- departamento (helper is_dept_leader() ya existente).
-- Esta migración SOLO crea estructura; la carga de datos va en una migración aparte.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Uniformes formales que posee cada servidor ────────────────────────────
-- Solo se evalúa en domingos. Sin filas y sirviendo domingo ⇒ no califica.
create table if not exists public.servidor_uniformes (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  uniforme_id bigint not null references public.uniformes_departamento(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (usuario_id, uniforme_id)
);

-- ── 2. Whitelist de posiciones permitidas ────────────────────────────────────
-- Sin filas para un usuario ⇒ puede ir a cualquier posición (sin restricción).
-- solo_semana_adoracion = true ⇒ la whitelist solo aplica en semana de adoración
-- (caso "Dunia López solo baño cuando es semana de adoración").
create table if not exists public.servidor_posiciones_permitidas (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  posicion_id bigint not null references public.posiciones_departamento(id) on delete cascade,
  solo_semana_adoracion boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  unique (usuario_id, posicion_id)
);

-- ── 3. Grupos de incompatibilidad ────────────────────────────────────────────
-- Máximo un miembro del grupo asignado por día (caso John/Josué/Noyling).
create table if not exists public.grupos_incompatibilidad (
  id bigint generated by default as identity primary key,
  nombre text not null,
  departamento_id bigint not null default 2 references public.departamentos(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.grupos_incompatibilidad_miembros (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos_incompatibilidad(id) on delete cascade,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  unique (grupo_id, usuario_id)
);

-- ── 4. Restricciones por servidor (tabla central) ────────────────────────────
-- tipo:
--   liderazgo_externo    → cada 3 meses + solo entre semana + libre en adoración.
--                          motivo guarda el cargo (ej. "Líder Red de Mujeres").
--   frecuencia_meses     → sirve a lo sumo cada valor_int meses.
--   max_por_mes          → máximo valor_int por mes; dia_tipo acota a domingo /
--                          entre_semana / NULL (total).
--   siempre_libre        → excluido del automático (incluible manual).
--   rotativo             → horario rotativo; excluido del automático.
--   requiere_confirmacion→ "preguntar qué día" antes de asignar.
--   dias_bloqueados      → valor_texto = días de la semana bloqueados, CSV 0..6
--                          (0=domingo … 6=sábado). Ej. "solo entre semana" = "0,6";
--                          "no domingos" = "0"; "no martes y jueves" = "2,4".
create table if not exists public.restricciones_servidor (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  departamento_id bigint not null default 2 references public.departamentos(id) on delete cascade,
  tipo text not null,
  valor_int integer,
  valor_texto text,
  dia_tipo text,
  solo_semana_adoracion boolean not null default false,
  motivo text,
  activa boolean not null default true,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default timezone('utc', now()),
  constraint restricciones_servidor_tipo_check check (tipo in (
    'liderazgo_externo','frecuencia_meses','max_por_mes',
    'siempre_libre','rotativo','requiere_confirmacion','dias_bloqueados'
  )),
  constraint restricciones_servidor_dia_tipo_check check (
    dia_tipo is null or dia_tipo in ('domingo','entre_semana')
  )
);

-- ── 5. Override manual en asignaciones ───────────────────────────────────────
-- Permite registrar que un servidor restringido fue incluido a propósito.
alter table public.asignaciones
  add column if not exists override_restriccion boolean not null default false;

-- ── Índices ──────────────────────────────────────────────────────────────────
create index if not exists idx_restricciones_servidor_usuario
  on public.restricciones_servidor(usuario_id) where activa;
create index if not exists idx_servidor_uniformes_usuario
  on public.servidor_uniformes(usuario_id);
create index if not exists idx_servidor_posiciones_usuario
  on public.servidor_posiciones_permitidas(usuario_id);
create index if not exists idx_grupos_incomp_miembros_usuario
  on public.grupos_incompatibilidad_miembros(usuario_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────────────────────────────────────────

-- servidor_uniformes
alter table public.servidor_uniformes enable row level security;
create policy "servidor_uniformes_select_authenticated"
  on public.servidor_uniformes for select to authenticated using (true);
create policy "servidor_uniformes_write_leader_or_admin"
  on public.servidor_uniformes for all to authenticated
  using (public.is_dept_leader(2))
  with check (public.is_dept_leader(2));

-- servidor_posiciones_permitidas
alter table public.servidor_posiciones_permitidas enable row level security;
create policy "servidor_posiciones_select_authenticated"
  on public.servidor_posiciones_permitidas for select to authenticated using (true);
create policy "servidor_posiciones_write_leader_or_admin"
  on public.servidor_posiciones_permitidas for all to authenticated
  using (public.is_dept_leader(2))
  with check (public.is_dept_leader(2));

-- grupos_incompatibilidad
alter table public.grupos_incompatibilidad enable row level security;
create policy "grupos_incompatibilidad_select_authenticated"
  on public.grupos_incompatibilidad for select to authenticated using (true);
create policy "grupos_incompatibilidad_write_leader_or_admin"
  on public.grupos_incompatibilidad for all to authenticated
  using (public.is_dept_leader(departamento_id))
  with check (public.is_dept_leader(departamento_id));

-- grupos_incompatibilidad_miembros
alter table public.grupos_incompatibilidad_miembros enable row level security;
create policy "grupos_incomp_miembros_select_authenticated"
  on public.grupos_incompatibilidad_miembros for select to authenticated using (true);
create policy "grupos_incomp_miembros_write_leader_or_admin"
  on public.grupos_incompatibilidad_miembros for all to authenticated
  using (public.is_dept_leader(2))
  with check (public.is_dept_leader(2));

-- restricciones_servidor
alter table public.restricciones_servidor enable row level security;
create policy "restricciones_servidor_select_authenticated"
  on public.restricciones_servidor for select to authenticated using (true);
create policy "restricciones_servidor_write_leader_or_admin"
  on public.restricciones_servidor for all to authenticated
  using (public.is_dept_leader(departamento_id))
  with check (public.is_dept_leader(departamento_id));
