-- v2: blacklist de posiciones, co-asignación, scope de grupos de incompatibilidad

-- 1) Posiciones: modo permitida (whitelist) o bloqueada (blacklist)
alter table public.servidor_posiciones_permitidas
  add column if not exists modo text not null default 'permitida';
alter table public.servidor_posiciones_permitidas
  drop constraint if exists servidor_posiciones_modo_check;
alter table public.servidor_posiciones_permitidas
  add constraint servidor_posiciones_modo_check check (modo in ('permitida','bloqueada'));

-- 2) Grupos de incompatibilidad: scope por tipo de día + máximo por día
--    max_por_dia permite "máximo N del grupo por día" (ej. alabanza: 1 por domingo)
alter table public.grupos_incompatibilidad
  add column if not exists dia_tipo text,
  add column if not exists max_por_dia integer not null default 1;
alter table public.grupos_incompatibilidad
  drop constraint if exists grupos_incompatibilidad_dia_tipo_check;
alter table public.grupos_incompatibilidad
  add constraint grupos_incompatibilidad_dia_tipo_check
  check (dia_tipo is null or dia_tipo in ('domingo','entre_semana'));

-- 3) Co-asignación (preferente): servidores que deberían servir juntos
create table if not exists public.grupos_coasignacion (
  id bigint generated by default as identity primary key,
  nombre text not null,
  departamento_id bigint not null default 2 references public.departamentos(id) on delete cascade,
  obligatorio boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);
create table if not exists public.grupos_coasignacion_miembros (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos_coasignacion(id) on delete cascade,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  unique (grupo_id, usuario_id)
);
create index if not exists idx_coasignacion_miembros_usuario
  on public.grupos_coasignacion_miembros(usuario_id);

alter table public.grupos_coasignacion enable row level security;
create policy "grupos_coasignacion_select_authenticated"
  on public.grupos_coasignacion for select to authenticated using (true);
create policy "grupos_coasignacion_write_leader"
  on public.grupos_coasignacion for all to authenticated
  using (public.is_dept_leader(departamento_id))
  with check (public.is_dept_leader(departamento_id));

alter table public.grupos_coasignacion_miembros enable row level security;
create policy "grupos_coasignacion_miembros_select_authenticated"
  on public.grupos_coasignacion_miembros for select to authenticated using (true);
create policy "grupos_coasignacion_miembros_write_leader"
  on public.grupos_coasignacion_miembros for all to authenticated
  using (public.is_dept_leader(2))
  with check (public.is_dept_leader(2));
